version: "1.0"
cluster: "default"

topology:
  roles:
    controlplane: "node-role.kubernetes.io/control-plane"
    etcd: "node-role.kubernetes.io/etcd"
    worker: "node-role.kubernetes.io/worker"

matrix:
  internal:
    - from: "controlplane"
      to: "worker"
      ports: [ 10250 ]
      proto: "tcp"
    - from: "worker"
      to: "worker"
      ports: [ 8472 ]
      proto: "udp"
    - from: "worker"
      to: "worker"
      ports: [ 9500, 9501 ]
      proto: "tcp"

  external: []
